---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java6
    - java7
    - java
